<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ResultsTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('results')->insert([
            [
                'student_id'=>1,
                'class_id'=>1,
                'subject_id'=>1,
                'marks'=>85
            ],
             [
                'student_id'=>1,
                'class_id'=>1,
                'subject_id'=>2,
                'marks'=>90
            ],
             [
                'student_id'=>1,
                'class_id'=>1,
                'subject_id'=>3,
                'marks'=>100
            ],
             [
                'student_id'=>1,
                'class_id'=>1,
                'subject_id'=>4,
                'marks'=>92
            ],
             [
                'student_id'=>2,
                'class_id'=>1,
                'subject_id'=>1,
                'marks'=>78
            ],
             [
                'student_id'=>2,
                'class_id'=>1,
                'subject_id'=>2,
                'marks'=>81
            ],
             [
                'student_id'=>2,
                'class_id'=>1,
                'subject_id'=>3,
                'marks'=>92
            ],
             [
                'student_id'=>2,
                'class_id'=>1,
                'subject_id'=>4,
                'marks'=>81
            ],
             [
                'student_id'=>3,
                'class_id'=>1,
                'subject_id'=>1,
                'marks'=>61
            ],
             [
                'student_id'=>3,
                'class_id'=>1,
                'subject_id'=>2,
                'marks'=>75
            ],
             [
                'student_id'=>3,
                'class_id'=>1,
                'subject_id'=>3,
                'marks'=>67
            ],
             [
                'student_id'=>3,
                'class_id'=>1,
                'subject_id'=>4,
                'marks'=>75
            ],
             [
                'student_id'=>4,
                'class_id'=>1,
                'subject_id'=>1,
                'marks'=>56
            ],
             [
                'student_id'=>4,
                'class_id'=>1,
                'subject_id'=>2,
                'marks'=>91
            ],
             [
                'student_id'=>4,
                'class_id'=>1,
                'subject_id'=>3,
                'marks'=>78
            ],
             [
                'student_id'=>4,
                'class_id'=>1,
                'subject_id'=>4,
                'marks'=>86
            ],
             [
                'student_id'=>5,
                'class_id'=>2,
                'subject_id'=>1,
                'marks'=>81
            ],
             [
                'student_id'=>5,
                'class_id'=>2,
                'subject_id'=>2,
                'marks'=>81
            ],
             [
                'student_id'=>5,
                'class_id'=>2,
                'subject_id'=>3,
                'marks'=>76
            ],
             [
                'student_id'=>5,
                'class_id'=>2,
                'subject_id'=>4,
                'marks'=>79
            ],
             [
                'student_id'=>6,
                'class_id'=>2,
                'subject_id'=>1,
                'marks'=>74
            ],
             [
                'student_id'=>6,
                'class_id'=>2,
                'subject_id'=>2,
                'marks'=>81
            ],
             [
                'student_id'=>6,
                'class_id'=>2,
                'subject_id'=>3,
                'marks'=>80
            ],
            
             [
                'student_id'=>6,
                'class_id'=>2,
                'subject_id'=>4,
                'marks'=>91
            ],
             [
                'student_id'=>7,
                'class_id'=>2,
                'subject_id'=>1,
                'marks'=>92
            ],
             [
                'student_id'=>7,
                'class_id'=>2,
                'subject_id'=>2,
                'marks'=>81
            ],
             [
                'student_id'=>7,
                'class_id'=>2,
                'subject_id'=>3,
                'marks'=>89
            ],
             [
                'student_id'=>7,
                'class_id'=>2,
                'subject_id'=>4,
                'marks'=>89
            ]
        ]);
    }
}
